Repository MichelImpacta/devops-Aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#4 Integrar arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#6 V1.0 programacão
  src/jogovelha.py
Labels: programação

#8 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#12 Integrar requisitos v1.1
  docs/requisitosv1.1.md
Labels: análise

#14 Integrar requisitos v1.1
  docs/requisitos.md
  docs/requisitosv1.1.md
Labels: análise

#15 V1.1 programação da nova funcionalidade
  src/jogovelha.py
Labels: programação

#17 Integrar testes v1.1
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#16 programação da nova funcionalidade v1.1
  src/jogovelha.py
Labels: programação

#20 Integrar arquitetura v1.1
  docs/arquitetura.md
Labels: arquitetura
